### ISSUE TITLE
Consider to drop mimalloc

### ISSUE THREAD

**Issue by gi0baro** [emmett-framework/granian#121]
Given
- https://github.com/pydantic/pydantic-core/pull/900
- https://github.com/gi0baro/geohashr/pull/3

it seems mimalloc causes large virtual memory allocations.

Some quick tests on CPython 3.10 on Apple Silicon shows a few percentage points performance degradation (RPS) when switching to default allocator.

Before a drop/replacement action I'd like to make more tests on memory usage and performance degradation, gonna update this in the process.

**Comment by Aeron** [comment]
My two cents, if I may:

- Mimalloc is still a viable solution for MUSL-based platforms since the default allocator there is not very efficient;
- Also, CPython kind of moves towards Mimalloc potentially (python/cpython/pull/31164).

The latter might be irrelevant to any decision here, just a curious fact.

**Comment by gi0baro** [comment]
> * Mimalloc is still a viable solution for MUSL-based platforms since the default allocator there is not very efficient;

We can definitely use mimalloc just on MUSL builds.
Anyways, this is just a reminder for myself, before taking any decision I gonna update this with benchmarks and profiling results :)
