### ISSUE TITLE
Workers are not restarted when killed by signal or exit

### ISSUE THREAD

**Issue by aldem** [emmett-framework/granian#148]
Not sure if this is intended behavior (I would be surprised), but if worker is dying it is not restarted and there is even no log message written, the app is simply not responding anymore (connection refused), it also leaves a zombie process which is not collected.

Using of external process manager is not an option as the main process is still there.

While full-pledged process management is a bit of effort, simple restart of a worker if it exits or killed would really help - apps are not bullet-proof and there are many things that can go wrong.

Or, optionally, when using a single worker, the main process should exit if worker exits or killed - then it would allow to use external process management (maybe).

**Comment by gi0baro** [comment]
Hi @aldem, this is not a behaviour intended by design, but rather the "actual state" of granian considering the lifespan of the project and the amount of contributions received :)

I'm quite against altering the server behaviour in case of just one worker, those things tend to be hard to debug in case of errors.

What I would do instead is actually to make the master process be aware of what happens to workers and behave accordingly, maybe we can even make this configurable with a parameter like `respawn_workers = True`, having the master process to respawn workers if the parameter says so and exit otherwise.

I'm not sure when this will actually land though, as I'm currently focused on the Hyper 1.0 theme, so unless someone wants to contribute on this immediately, I'll look at it after I ended with the other themes.
