### ISSUE TITLE
It's undocumented/unclear that --access-log does nothing unless Python logging is configured

### ISSUE THREAD

**Issue by hynek** [emmett-framework/granian#418]
Hi,

while trying to debug a problem, I wanted to activate access logging and it took me quite a while until I grokked that it's (unlike other output) dependent on my Python `logging` configuration.

I think that should be pointed out.

**Comment by gi0baro** [comment]
Given the default behaviour in Granian is to configure logging, this sounds quite an edge-case to me.

> I think that should be pointed out.

Can you expand on that? Like, where you'd like to find that information.

**Comment by hynek** [comment]
Oof OK based on my other ticket I've finally somewhat understood what's going on, but I still find it profoundly confusing. :)

There seems to be different types of logging within Granian, because for example on startup I get:

```
[INFO] Websockets are not supported on WSGI, ignoring
[INFO] Starting granian (main PID: 7)
[INFO] Listening at: https://0.0.0.0:31882
[INFO] Spawning worker-1 with pid: 11
```

then I got the errors mentioned in #419 which had a different format and my own logs that have different format still.

I honestly did not expect such strong interactions between my WSGI server and my `logging` setup – even less seeing seeing Rust log messages moved through is.

So I guess what I'd like is a paragraph or two explaining what Granian is doing in the first place and how it interacts with my own logging setup? From looking at it (and the different logging styles) I surmised there's isolated systems which doesn't seem to be the case.

**Comment by gi0baro** [comment]
@hynek sorry for the late reply

> I honestly did not expect such strong interactions between my WSGI server and my `logging` setup – even less seeing seeing Rust log messages moved through is.
> 
> So I guess what I'd like is a paragraph or two explaining what Granian is doing in the first place and how it interacts with my own logging setup? From looking at it (and the different logging styles) I surmised there's isolated systems which doesn't seem to be the case.

I'm not sure I get this big difference in Granian when compared to other servers. I can't confirm this, but I'm pretty sure the approach is quite similar to other projects like uvicorn, hypercorn and gunicorn, where you have access logs separated from the rest. The fact Rust logs gets routed through Python logging is to allow users to customise the format/level of those messages, that would otherwise not be possible (or at least not with a familiar syntax for Python users).

In terms of logging, Granian set up two loggers with specific names (https://github.com/emmett-framework/granian/blob/master/granian/log.py#L28-L51), so they *should* theoretically be isolated from other loggers.
Maybe it's because the formatters and handlers have common names and can be overridden to easily by users? Would changing those names into some `_granian` prefixed names solves the discrepancies you experienced?

**Comment by gi0baro** [comment]
> To be clear, I'm not asking you to change any behavior, I'm asking you to clearly state that "granian logs using stdlib logging, using logger names X, Y, and Z."

Would you open a PR for that, just to place the message you expected, then I'll add details on loggers name?
